### ISSUE TITLE
Unable to resolve the plugin package

### ISSUE THREAD

**Issue by biancoda** [RoadieHQ/backstage-plugin-github#12]
Hi, this plugin was suggested by the Backstage team.
I'm trying to add it to my Backstage environment, but I got an error when it tries to resolve the package.

```
root@backstage-dev:/opt/backstage-dxc-app/packages/app# yarn add @roadiehq/backstage-plugin-github
yarn add v1.22.5
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@roadiehq%2fbackstage-plugin-github: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/opt/backstage-dxc-app/packages/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

From the yarn-error.log, I got this:
```
Arguments:
  /root/.nvm/versions/node/v14.15.3/bin/node /usr/share/yarn/bin/yarn.js add @roadiehq/backstage-plugin-github

PATH:
  /root/.nvm/versions/node/v14.15.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

Yarn version:
  1.22.5

Node version:
  14.15.3

Platform:
  linux x64

Trace:
  Error: https://registry.yarnpkg.com/@roadiehq%2fbackstage-plugin-github: Not found
      at Request.params.callback [as _callback] (/usr/share/yarn/lib/cli.js:66988:18)
      at Request.self.callback (/usr/share/yarn/lib/cli.js:140749:22)
      at Request.emit (events.js:315:20)
      at Request.<anonymous> (/usr/share/yarn/lib/cli.js:141721:10)
      at Request.emit (events.js:315:20)
      at IncomingMessage.<anonymous> (/usr/share/yarn/lib/cli.js:141643:12)
      at Object.onceWrapper (events.js:421:28)
      at IncomingMessage.emit (events.js:327:22)
      at endReadableNT (internal/streams/readable.js:1327:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

I don't see it on the backstage marketplace, is it avaible?

Thanks

**Comment by dtuite** [comment]
Hi @biancoda. Apologies for the confusion. This plugin is deprecated, although we don't seem to have mentioned that on the README.

This plugin was intended to be a wrapper package around our other GitHub plugins (pull requests, insights etc.) so that a user could install one package and be able to use the widgets and tabs from all of those wrapped plugins. It doesn't have any features of it's own.

We will indicate this plugin is deprecated on the README. Please use our other GitHub plugins individually instead.

**Comment by dtuite** [comment]
I have opened #13 to prevent further confusion.
